/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-06-18 02:30:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ITWILLJOIN_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tfunction onJoinCheck() {\r\n");
      out.write("\t\t/* 아이디 확인 */\r\n");
      out.write("\t\tif(document.fr.id.value==\"\"){\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\tdocument.fr.id.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 아이디 5~10자리 확인 */\r\n");
      out.write("\t\tif((document.fr.id.value.length < 5) || (document.fr.id.value.length>10)){\r\n");
      out.write("\t\t\talert(\"아이디는 5~10자리 이내로 입력하세요.\");\r\n");
      out.write("\t\t\tdocument.fr.id.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 비밀번호 입력여부 확인 */\r\n");
      out.write("\t\tif(document.fr.pass1.value==\"\"){\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("\t\t\tdocument.fr.pass1.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.fr.pass2.value==\"\"){\r\n");
      out.write("\t\t\talert(\"비밀번호 확인란을 입력해주세요.\");\r\n");
      out.write("\t\t\tdocument.fr.pass2.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!(document.fr.pass1.value == document.fr.pass2.value)){\r\n");
      out.write("\t\t\talert(\"비밀번호가 서로 일치하지 않습니다.\");\r\n");
      out.write("\t\t\tdocument.fr.pass1.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 이름 확인 */\r\n");
      out.write("\t\tif(document.fr.name.value==\"\"){\r\n");
      out.write("\t\t\talert(\"이름을 입력해주세요.\");\r\n");
      out.write("\t\t\tdocument.fr.name.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 주민번호 확인 */\r\n");
      out.write("\t\tif(document.fr.jumin1.value.length != 6 ){\r\n");
      out.write("\t\t\talert(\"주민번호 앞자리는 6자리 입니다\");\r\n");
      out.write("\t\t\tdocument.fr.jumin1.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.fr.jumin2.value.length != 7){\r\n");
      out.write("\t\t\talert(\"주민번호 뒷자리는 7자리 입니다\");\r\n");
      out.write("\t\t\tdocument.fr.jumin2.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 성별 체크 */\r\n");
      out.write("\t\tif(document.fr.gender[0].checked == false && \r\n");
      out.write("\t\t\t\tdocument.fr.gender[1].checked == false) {\r\n");
      out.write("\t\t\talert(\"성별을 체크하세요\");\r\n");
      out.write("\t\t\tdocument.fr.gender[0].focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 주민번호 확인 */\r\n");
      out.write("\t\tif(document.fr.hobby[0].checked == false &&\r\n");
      out.write("\t\t\t\tdocument.fr.hobby[1].checked == false && \r\n");
      out.write("\t\t\t\tdocument.fr.hobby[2].checked == false ){\r\n");
      out.write("\t\t\talert(\"취미를 체크하세요\");\r\n");
      out.write("\t\t\tdocument.fr.hobby[0].focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 과목 선택 확인 */\r\n");
      out.write("\t\tvar idx = document.fr.subject.selectedIndex;\r\n");
      out.write("\t\tif(document.fr.subject.options[idx].value == \"\" ){\r\n");
      out.write("\t\t\talert(\"과목을 선택하세요\");\r\n");
      out.write("\t\t\tdocument.fr.subject.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 메모 입력 확인 */\r\n");
      out.write("\t\tif(document.fr.comment.value == \"\"){\r\n");
      out.write("\t\t\talert(\"남기고 싶은 말을 입력하세요\");\r\n");
      out.write("\t\t\tdocument.fr.comment.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 성별 자동 체크 */\r\n");
      out.write("\tfunction onCheckGender() {\r\n");
      out.write("\t\tvar s = document.fr.jumin2.value.charAt(0);\r\n");
      out.write("\t\tif(s == 1 || s==3) document.fr.gender[0].checked=true;\r\n");
      out.write("\t\tif(s == 2 || s==4) document.fr.gender[1].checked=true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1> 회원가입 : 2강의실 김지원 </h1>\r\n");
      out.write("<form action=\"ITWILLJOINPRO.jsp\" name=\"fr\" method=\"post\" onsubmit=\"return onJoinCheck()\">\r\n");
      out.write("<fieldset>\r\n");
      out.write("\t<legend>ITWILL 회원가입</legend>\r\n");
      out.write("\t\r\n");
      out.write("\t아이디 : <input type=\"text\" name=\"id\"><br>\r\n");
      out.write("\t비밀번호 : <input type=\"password\" name=\"pass1\"><br>\r\n");
      out.write("\t비밀번호 확인 : <input type=\"password\" name=\"pass2\"><br>\r\n");
      out.write("\t이름 : <input type=\"text\" name=\"name\"> <br>\r\n");
      out.write("\t주민번호 : <input type=\"text\" name=\"jumin1\">-<input type=\"password\" name=\"jumin2\" onKeyUp=\"onCheckGender()\"><br>\r\n");
      out.write("\t성별 : <input type=\"radio\" name=\"gender\" value=\"남\">남\r\n");
      out.write("\t\t   <input type=\"radio\" name=\"gender\" value=\"여\">여 <br>\r\n");
      out.write("\t취미 : <input type=\"checkbox\" name=\"hobby\" value=\"여행\">여행\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"hobby\" value=\"독서\">독서\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"hobby\" value=\"영화감상\">영화감상<br>\r\n");
      out.write("\t좋아하는 과목 :\r\n");
      out.write("\t<select name=\"subject\">\r\n");
      out.write("\t\t<option value=\"\">선택하세요.</option>\r\n");
      out.write("\t\t<option value=\"jsp\">JSP</option>\r\n");
      out.write("\t\t<option value=\"Java\">Java</option>\r\n");
      out.write("\t\t<option value=\"Android\">Android</option>\r\n");
      out.write("\t\t<option value=\"Web\">Web</option>\r\n");
      out.write("\t\t<option value=\"DataBase\">DataBase</option>\r\n");
      out.write("\t</select> <br> \r\n");
      out.write("\t\r\n");
      out.write("\t한마디 : <textarea rows=\"10\" cols=\"100\" name=\"comment\"></textarea>\r\n");
      out.write("\t\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"submit\" value=\"회원가입\">\r\n");
      out.write("\t<input type=\"reset\" value=\"처음으로\">\r\n");
      out.write("</fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
